version: "3.8"
services:
    factorio:
        image: hanse01/factorio-container:${FACTORIO_VERSION:-stable}
        build:
            context: .
            args:
                version: ${FACTORIO_VERSION:-stable}
